version: "3"
services:
  service-discovery:
    image: "serhiibabanov/service-discovery:latest"
    container_name: "service-discovery"
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - pottery_store
  backend-gateway:
    image: "serhiibabanov/backend-gateway:latest"
    container_name: "backend-gateway"
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - service-discovery
    networks:
      - pottery_store
  service-products:
    image: "serhiibabanov/service-products:latest"
    container_name: "service-products"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/potterystore
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      - database
      - service-discovery
    restart: on-failure
    networks:
      - pottery_store
  database:
    container_name: "database"
    build:
      context: ./database-image
      dockerfile: "Dockerfile"
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=potterystore
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - pottery_store
  docs:
    image: "serhiibabanov/docs:latest"
    container_name: "docs"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8082:8082"
    depends_on:
      - service-products
    networks:
      - pottery_store
networks:
  pottery_store:
