server:
  port: 0
  servlet:
    context-path: /api

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application.name: service-subscribe
  datasource:
    url: ${DATABASE_URL}
    username: service_subscribe
    password: srv-sbs
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: /db/{vendor}/common

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

