server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application:
    name: backend-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-products-id
          uri: lb://service-products
          predicates:
            - Path=/api/products/**
        - id: service-colors-id
          uri: lb://service-products
          predicates:
            - Path=/api/colors/**
        - id: service-categories-id
          uri: lb://service-products
          predicates:
            - Path=/api/categories/**
        - id: service-collections-id
          uri: lb://service-products
          predicates:
            - Path=/api/collections/**
        - id: service-docs-id
          uri: lb://docs
          predicates:
              - Path=/docs/**
        - id: service-subscribe-id
          uri: lb://service-subscribe
          predicates:
            - Path=/api/subscribe
        - id: service-unsubscribe-id
          uri: lb://service-subscribe
          predicates:
            - Path=/api/unsubscribe
        - id: service-support-id
          uri: lb://service-support
          predicates:
            - Path=/api/support

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
