server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application:
    name: backend-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-products-id
          uri: lb://service-products
          predicates:
            - Path=/products/**
        - id: service-colors-id
          uri: lb://service-products
          predicates:
            - Path=/colors/**
        - id: service-categories-id
          uri: lb://service-products
          predicates:
            - Path=/categories/**
        - id: service-collections-id
          uri: lb://service-products
          predicates:
            - Path=/collections/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
