server:
  port: 0
  servlet:
    context-path: /products

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application.name: service-products
  datasource:
    url: jdbc:postgresql://localhost:5432/potterystore
    username: service_products
    password: srv-pds
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
