server:
  port: 0

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application.name: service-products
  datasource:
    url: ${DATABASE_URL}
    username: service_products
    password: srv-pds
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 24

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
