name: build and run pottery-api
on:
  push:
    branches:
      - dev

jobs:
  test_build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          appdir: "backend-gateway"
      - name: Make gradlew executable
        run: chmod +x backend-gateway/gradlew
      - name: Execute Gradle build
        run: backend-gateway/gradlew build

  docker:
    name: build docker image backend-gateway
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          appdir: "backend-gateway"

      - name: Make gradlew executable
        run: |
          chmod +x backend-gateway/gradlew
      - name: Execute Gradle bootBuildImage
        run: ./gradlew bootBuildImage --imageName=serhiibabanov/pottery_store:backend-gateway
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: serhiibabanov
      - name: Push Docker image to Nexus registry
        run: docker push serhiibabanov/pottery_store:backend-gateway
