name: Deploy on self-hosted runner
on:
  workflow_dispatch:
    branches: ['dev']

jobs:
    deploy:
        runs-on: self-hosted
        steps:
        - name: Checkout files
          uses: Bhacaz/checkout-files@v2
          with:
            branch: dev
            files: compose.yml database-image
        - name: Deploy
          run: |
            docker compose pull
            docker compose up -d
            docker system prune -af
