name: build and run pottery-api
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: shutdown any running containers
        run: docker-compose down

      - name: start the docker containers
        run: docker-compose up --build -d
