name: build and run pottery-api
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: self-hosted
    steps:
      # The "cleanup old checkout" step is needed because of this bug: https://github.com/actions/checkout/issues/1014
      - name: cleanup old checkout
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Check out repository
        uses: actions/checkout@v4

      - name: shutdown any running containers
        run: docker compose down

      - name: Make gradlew executable
        run: chmod +x backend-gateway/gradlew
      - name: Make gradlew executable
        run: chmod +x service-discovery/gradlew
      - name: Make gradlew executable
        run: chmod +x service-products/gradlew

      - name: start the docker containers
        run: docker compose up --build -d
