name: build and run pottery-api
on: workflow_dispatch

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: shutdown any running containers
        run: docker compose down

      - name: Make gradlew executable
        run: chmod +x backend-gateway/gradlew
      - name: Make gradlew executable
        run: chmod +x service-discovery/gradlew
      - name: Make gradlew executable
        run: chmod +x service-products/gradlew

      - name: start the docker containers
        run: docker compose up --build -d
