name: publish service-discovery
on:
  push:
    branches: ['dev']
    paths: ['service-discovery/**']

jobs:
  test_build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: service-discovery
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build

  docker:
    needs: test_build
    name: build docker image service-discovery
    runs-on: self-hosted
    defaults:
      run:
        working-directory: service-discovery
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew
      - name: Execute Gradle bootBuildImage
        run: ./gradlew bootBuildImage
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push serhiibabanov/service-discovery:latest
